"""up

Revision ID: 44ac0cc73de2
Revises: 46e267dfcff4
Create Date: 2025-05-30 12:31:05.285665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44ac0cc73de2'
down_revision: Union[str, None] = '46e267dfcff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('is_registered', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_registered')
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###
