"""er[A

Revision ID: ba78d31e954d
Revises: 44ac0cc73de2
Create Date: 2025-05-30 12:35:30.593155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba78d31e954d'
down_revision: Union[str, None] = '44ac0cc73de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_online')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_online', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
