"""update

Revision ID: f0dbf6b0ea57
Revises: cc38a994361a
Create Date: 2025-05-27 14:41:44.898964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0dbf6b0ea57'
down_revision: Union[str, None] = 'cc38a994361a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'post_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('post_code', sa.VARCHAR(length=80), nullable=False))
    # ### end Alembic commands ###
